@startuml
!include <aws/common>
header Netzwerk Diagramm

title Struktur pro Availability Zone

node "Availability Zone" as az {
    artifact "Privates Otto Subnet" as private_sub
    node "Router" as router
    artifact "Privates cluster subnet" as cluster_sub

    artifact "Cluster worker" as cluster_worker
    artifact "Privater Load balancer\nErreichbar im Otto-Net" as load_balancer

    private_sub <-right-> router
    private_sub -down-> load_balancer
    router <-right-> cluster_sub
    cluster_sub -down-> cluster_worker
}
@enduml
