@startuml
title Speichern einer Aktion über das FE

participant FrontEnd as FE
participant Backend as B
participant ActionApp as A
database ActionDatabase as Db
participant RabbitMq as R

FE --> B: Aktion speichern
B --> A: Aktion speichern
A --> Db: Aktion speichern
A --> A: interne Caches updaten
A --> B: gespeicherte AktionView
B --> R: Items der Aktion in die Queue legen
B --> FE: AktionView


@enduml