name: Delete all untagged images from ghcr.io

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 3'

permissions:
  contents: read
  packages: write

jobs:
  delete-imgages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: user